name: sm_retry
description: "Retry asynchronous functions with exponential backoff"
homepage: https://github.com/shay-wong/flutter_sm_retry
repository: https://github.com/shay-wong/flutter_sm_retry
issue_tracker: https://github.com/shay-wong/flutter_sm_retry/issues
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.25.0

topics:
  - retry
  - http
  - network
  - backoff
